name: ncd_mobile
description: Cross-platform app for early detection and management of NCDs
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  provider: ^6.1.2
  shared_preferences: ^2.5.3
  fl_chart: ^0.68.0
  url_launcher: ^6.3.1
  supabase_flutter: ^2.3.4
  flutter_dotenv: ^5.1.0
  intl: ^0.18.1
  uuid: ^4.5.1
  # Chat functionality
  socket_io_client: ^2.0.3+1
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  flutter_chat_ui: ^1.6.12
  connectivity_plus: ^5.0.2
  flutter_local_notifications: ^16.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env

