# Generated by Django 5.2.5 on 2025-09-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patientprofile_address_patientprofile_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientprofile',
            options={'verbose_name_plural': 'Patient Profiles'},
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('provider', 'Provider'), ('worker', 'Community Health Worker')], default='patient', max_length=20),
        ),
    ]
