version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ncd
      POSTGRES_USER: ncd
      POSTGRES_PASSWORD: ncdpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ncd"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    environment:
      DJANGO_SETTINGS_MODULE: ncd_app.settings
      SECRET_KEY: ${SECRET_KEY:-changeme}
      DEBUG: 'False'
      DATABASE_URL: postgres://ncd:ncdpass@db:5432/ncd
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      CORS_ALLOW_ALL_ORIGINS: 'False'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"

  worker:
    build: .
    command: ["bash", "-lc", "celery -A ncd_app worker -l info"]
    environment:
      DJANGO_SETTINGS_MODULE: ncd_app.settings
      DATABASE_URL: postgres://ncd:ncdpass@db:5432/ncd
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - web

  beat:
    build: .
    command: ["bash", "-lc", "celery -A ncd_app beat -l info"]
    environment:
      DJANGO_SETTINGS_MODULE: ncd_app.settings
      DATABASE_URL: postgres://ncd:ncdpass@db:5432/ncd
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - web

volumes:
  pgdata:


